sound_a = new Audio("/res/audio/Gojuuon-a.wav")
sound_i = new Audio("/res/audio/Gojuuon-i.wav")
sound_u = new Audio("/res/audio/Gojuuon-u.wav")
sound_e = new Audio("/res/audio/Gojuuon-e.wav")
sound_o = new Audio("/res/audio/Gojuuon-o.wav")
sound_ka = new Audio("/res/audio/Gojuuon-ka.wav")
sound_ki = new Audio("/res/audio/Gojuuon-ki.wav")
sound_ku = new Audio("/res/audio/Gojuuon-ku.wav")
sound_ke = new Audio("/res/audio/Gojuuon-ke.wav")
sound_ko = new Audio("/res/audio/Gojuuon-ko.wav")
sound_sa = new Audio("/res/audio/Gojuuon-sa.wav")
sound_shi = new Audio("/res/audio/Gojuuon-shi.wav")
sound_su = new Audio("/res/audio/Gojuuon-su.wav")
sound_se = new Audio("/res/audio/Gojuuon-se.wav")
sound_so = new Audio("/res/audio/Gojuuon-so.wav")
sound_ta = new Audio("/res/audio/Gojuuon-ta.wav")
sound_chi = new Audio("/res/audio/Gojuuon-chi.wav")
sound_tsu = new Audio("/res/audio/Gojuuon-tsu.wav")
sound_te = new Audio("/res/audio/Gojuuon-te.wav")
sound_to = new Audio("/res/audio/Gojuuon-to.wav")
sound_ma = new Audio("/res/audio/Gojuuon-ma.wav")
sound_mi = new Audio("/res/audio/Gojuuon-mi.wav")
sound_mu = new Audio("/res/audio/Gojuuon-mu.wav")
sound_me = new Audio("/res/audio/Gojuuon-me.wav")
sound_mo = new Audio("/res/audio/Gojuuon-mo.wav")
sound_ha = new Audio("/res/audio/Gojuuon-ha.wav")
sound_hi = new Audio("/res/audio/Gojuuon-hi.wav")
sound_fu = new Audio("/res/audio/Gojuuon-fu.wav")
sound_he = new Audio("/res/audio/Gojuuon-he.wav")
sound_ho = new Audio("/res/audio/Gojuuon-ho.wav")
sound_na = new Audio("/res/audio/Gojuuon-na.wav")
sound_ni = new Audio("/res/audio/Gojuuon-ni.wav")
sound_nu = new Audio("/res/audio/Gojuuon-nu.wav")
sound_ne = new Audio("/res/audio/Gojuuon-ne.wav")
sound_no = new Audio("/res/audio/Gojuuon-no.wav")
sound_ya = new Audio("/res/audio/Gojuuon-ya.wav")
sound_yu = new Audio("/res/audio/Gojuuon-yu.wav")
sound_yo = new Audio("/res/audio/Gojuuon-yo.wav")
sound_ra = new Audio("/res/audio/Gojuuon-ra.wav")
sound_ri = new Audio("/res/audio/Gojuuon-ri.wav")
sound_ru = new Audio("/res/audio/Gojuuon-ru.wav")
sound_re = new Audio("/res/audio/Gojuuon-re.wav")
sound_ro = new Audio("/res/audio/Gojuuon-ro.wav")
sound_wa = new Audio("/res/audio/Gojuuon-wa.wav")
sound_wo = new Audio("/res/audio/Gojuuon-wo.wav")
sound_n = new Audio("/res/audio/Gojuuon-n.wav")

sound_ga = new Audio("/res/audio/Gojuuon2-ga.wav")
sound_gi = new Audio("/res/audio/Gojuuon2-gi.wav")
sound_gu = new Audio("/res/audio/Gojuuon2-gu.wav")
sound_ge = new Audio("/res/audio/Gojuuon2-ge.wav")
sound_go = new Audio("/res/audio/Gojuuon2-go.wav")
sound_za = new Audio("/res/audio/Gojuuon2-za.wav")
sound_ji = new Audio("/res/audio/Gojuuon2-ji.wav")
sound_zu = new Audio("/res/audio/Gojuuon2-zu.wav")
sound_ze = new Audio("/res/audio/Gojuuon2-ze.wav")
sound_zo = new Audio("/res/audio/Gojuuon2-zo.wav")
sound_da = new Audio("/res/audio/Gojuuon2-da.wav")
sound_di = new Audio("/res/audio/Gojuuon2-di.wav")
sound_dzu = new Audio("/res/audio/Gojuuon2-dzu.wav")
sound_de = new Audio("/res/audio/Gojuuon2-de.wav")
sound_do = new Audio("/res/audio/Gojuuon2-do.wav")
sound_ba = new Audio("/res/audio/Gojuuon2-ba.wav")
sound_bi = new Audio("/res/audio/Gojuuon2-bi.wav")
sound_bu = new Audio("/res/audio/Gojuuon2-bu.wav")
sound_be = new Audio("/res/audio/Gojuuon2-be.wav")
sound_bo = new Audio("/res/audio/Gojuuon2-bo.wav")
sound_pa = new Audio("/res/audio/Gojuuon2-pa.wav")
sound_pi = new Audio("/res/audio/Gojuuon2-pi.wav")
sound_pu = new Audio("/res/audio/Gojuuon2-pu.wav")
sound_pe = new Audio("/res/audio/Gojuuon2-pe.wav")
sound_po = new Audio("/res/audio/Gojuuon2-po.wav")


function play_kana_sound(src_sound) {
	src_sound.play();
	//alert(src_sound.src);
}


